### ISSUE TITLE
英語ページを用意する

### ISSUE THREAD

**Issue by kou** [pgroonga/pgroonga.github.io#3]
* [x] https://github.com/pgroonga/pgroonga/blob/master/README.md を翻訳する
  * [x] README.mdの内容を分割して適切なパスに配置する #1
  * [x] 英語から日本語に翻訳する仕組みを導入する。参考: https://github.com/droonga/droonga.org
  * [x] 英語から日本語に翻訳する。（元の日本語の文章を利用する。）
  * [x] https://github.com/pgroonga/pgroonga/blob/master/README.md の内容を削除してpgroonga.github.ioにリンクを張る。

**Comment by uhyoppo** [comment]
翻訳しかけたんですが、似たような英文が既にあったので、もう要らないのかと思ってました。校正してないですけど、せっかくなんで貼っときますね。

# PGroonga (píːzí:lúnɡά)

## Release Information

Refer to [news.md](news.md)

## Overview

PGroonga is a PostgreSQL extension to use [Groonga](http://groonga.org/ja/) as the index.

As default, PostgreSQL is not capable for full-text-searching for Japanese text data. PGroonga can do with remarkable speed. Similar extensions are known for the full-text searching as below:

  * [pg_trgm](https://www.postgresql.jp/document/9.3/html/pgtrgm.html)
    * Bundled with PostgreSQL but not installed as default
    * Source code modification is required to adapt for Japanese
  * [pg_bigm](http://pgbigm.sourceforge.jp/)
    * Source code modification is NOT required to adapt for Japanese
    * But for the exact result:
      Enabling [Recheck function](http://pgbigm.sourceforge.jp/pg_bigm-1-1.html#enable_recheck) is mandantory.
    * If recheck is enabled, PostgreSQL will search using index, then search again sequentially against the result of the first search; therefore the cost tends to be increased if there are many results at the first searching.
    * If recheck is disabled, there are possibilities to match the records which doesn't include the keyword.

The modification of the original PostgreSQL source code is NOT required for PGroonga like pg\_trgm.

PGroonga can return the exact result without recheck like pg\_bigm. Therefore, the result using index which has many records, doesn't prevent the speed as pg\_bigm does. (Theoretically, the verification should be done using benchmark test. We need volunteers.)

However, at this stage, PGroonga doesn't mention to WAL, so it can't adapt to the crash recovery function and the replication. (pg\_trgm and pg\_bigm can act with them because GIN and GiST can do it, which are used in pg\_trgm and pg\_bigm.)

(*) Currently PostgreSQL doesn't provide API for the index as the extension functionalities to adapt to WAL. If such API would be provided, we will follow it immediately.

## PostgreSQL versions which can install Pgroonga

  * PostgreSQL 9.3
  * PostgreSQL 9.4

## Installation

We made the packages for the environments below:

  * Debian GNU/Linux Jessie
  * Ubuntu 14.04
  * Ubuntu 14.10
  * Ubuntu 15.04
  * CentOS 5
  * CentOS 6
  * CentOS 7
  * Windows 32bit + PostgreSQL 9.4.2
  * Windows 64bit + PostgreSQL 9.4.2

You must use the source code to install on the other environments.

Details of installation for each environment will continue at the next sections below.

**Comment by kou** [comment]
ありがとうございます！
発音記号なんかは私は絶対書けないやつなのでとても助かります！

今の翻訳に反映しました！

**Comment by kou** [comment]
Done!
