### ISSUE TITLE
Re: Cannot install groonga-tokenizer-mecab on CentOS8

### ISSUE THREAD

**Issue by s-araki-issp** [pgroonga/pgroonga.github.io#61]
Sorry for reposting even though it was closed.

In the following URL, "mecab-devel" package existed.
https://packages.groonga.org/centos/8/x86_64/Packages/
"mecab-devel" was able to install by executing the following command.
\# dnf install -y https://packages.groonga.org/centos/groonga-release-latest.noarch.rpm
\# dnf install mecab-devel

It seems that "mecab-devel" package is provided in groonga repository,
Does it mean that you need "mecab-devel" provided by CentOS8 (EPEL) to install groonga-tokenizer-mecab?
Or do you need "mecab-devel" provided by CentOS8 (EPEL) to create groonga-tokenizer-mecab package?

Thank you in advance.

**Comment by komainu8** [comment]
`mecab-devel` package that exists in the following URL is the unofficial one.

http://packages.groonga.org/centos/8/x86_64/Packages/mecab-devel-0.996-1.module_el8.0.0+41+ca30bab6.9.x86_64.rpm

We are not supported to make `groonga-tokenizer-mecab` by this package.
Because this package is made as a test.

Thus, we need `mecab-devel` package provided by CentOS8 (or EPEL) to make and install `groonga-tokenizer-mecab`.

Many thanks.

**Comment by s-araki-issp** [comment]
Thank you for your reply.
I understood the contents.

I hope "mecab-devel" will be released on CentOS8 (or EPEL).
https://bugs.centos.org/view.php?id=16668

I'm really thankful to you.
